# Generated by Django 3.1.3 on 2020-11-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participation', '0002_auto_20201119_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
    ]
