# Generated by Django 3.1.3 on 2020-11-19 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participation', '0006_auto_20201119_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email введен в неверном формате', regex='\\w[\\w\\.-] * @ \\w[\\w\\.-]+\\.\\w +')], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='Телефон введен в неверном формате', regex='[\\+\\(]?[1-9][0-9 .\\-\\(\\)]{8,}[0-9]')], verbose_name='Телефон'),
        ),
    ]
