# Generated by Django 3.1.3 on 2020-11-19 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participation', '0007_auto_20201120_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email введен в неверном формате', regex='\\w[\\w\\.-]*@\\w[\\w\\.-]+\\.\\w+')], verbose_name='E-mail'),
        ),
    ]
